# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/adriel/Documents/CELPE/ACS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/adriel/Documents/CELPE/ACS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adriel/Documents/CELPE/ACS/CMakeFiles /home/adriel/Documents/CELPE/ACS/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adriel/Documents/CELPE/ACS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named acs

# Build rule for target.
acs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 acs
.PHONY : acs

# fast build rule for target.
acs/fast:
	$(MAKE) -f CMakeFiles/acs.dir/build.make CMakeFiles/acs.dir/build
.PHONY : acs/fast

src/control/Attenuator.o: src/control/Attenuator.cpp.o

.PHONY : src/control/Attenuator.o

# target to build an object file
src/control/Attenuator.cpp.o:
	$(MAKE) -f CMakeFiles/acs.dir/build.make CMakeFiles/acs.dir/src/control/Attenuator.cpp.o
.PHONY : src/control/Attenuator.cpp.o

src/control/Attenuator.i: src/control/Attenuator.cpp.i

.PHONY : src/control/Attenuator.i

# target to preprocess a source file
src/control/Attenuator.cpp.i:
	$(MAKE) -f CMakeFiles/acs.dir/build.make CMakeFiles/acs.dir/src/control/Attenuator.cpp.i
.PHONY : src/control/Attenuator.cpp.i

src/control/Attenuator.s: src/control/Attenuator.cpp.s

.PHONY : src/control/Attenuator.s

# target to generate assembly for a file
src/control/Attenuator.cpp.s:
	$(MAKE) -f CMakeFiles/acs.dir/build.make CMakeFiles/acs.dir/src/control/Attenuator.cpp.s
.PHONY : src/control/Attenuator.cpp.s

src/control/Serial.o: src/control/Serial.cpp.o

.PHONY : src/control/Serial.o

# target to build an object file
src/control/Serial.cpp.o:
	$(MAKE) -f CMakeFiles/acs.dir/build.make CMakeFiles/acs.dir/src/control/Serial.cpp.o
.PHONY : src/control/Serial.cpp.o

src/control/Serial.i: src/control/Serial.cpp.i

.PHONY : src/control/Serial.i

# target to preprocess a source file
src/control/Serial.cpp.i:
	$(MAKE) -f CMakeFiles/acs.dir/build.make CMakeFiles/acs.dir/src/control/Serial.cpp.i
.PHONY : src/control/Serial.cpp.i

src/control/Serial.s: src/control/Serial.cpp.s

.PHONY : src/control/Serial.s

# target to generate assembly for a file
src/control/Serial.cpp.s:
	$(MAKE) -f CMakeFiles/acs.dir/build.make CMakeFiles/acs.dir/src/control/Serial.cpp.s
.PHONY : src/control/Serial.cpp.s

src/control/TAcs.o: src/control/TAcs.cpp.o

.PHONY : src/control/TAcs.o

# target to build an object file
src/control/TAcs.cpp.o:
	$(MAKE) -f CMakeFiles/acs.dir/build.make CMakeFiles/acs.dir/src/control/TAcs.cpp.o
.PHONY : src/control/TAcs.cpp.o

src/control/TAcs.i: src/control/TAcs.cpp.i

.PHONY : src/control/TAcs.i

# target to preprocess a source file
src/control/TAcs.cpp.i:
	$(MAKE) -f CMakeFiles/acs.dir/build.make CMakeFiles/acs.dir/src/control/TAcs.cpp.i
.PHONY : src/control/TAcs.cpp.i

src/control/TAcs.s: src/control/TAcs.cpp.s

.PHONY : src/control/TAcs.s

# target to generate assembly for a file
src/control/TAcs.cpp.s:
	$(MAKE) -f CMakeFiles/acs.dir/build.make CMakeFiles/acs.dir/src/control/TAcs.cpp.s
.PHONY : src/control/TAcs.cpp.s

src/control/TCommand.o: src/control/TCommand.cpp.o

.PHONY : src/control/TCommand.o

# target to build an object file
src/control/TCommand.cpp.o:
	$(MAKE) -f CMakeFiles/acs.dir/build.make CMakeFiles/acs.dir/src/control/TCommand.cpp.o
.PHONY : src/control/TCommand.cpp.o

src/control/TCommand.i: src/control/TCommand.cpp.i

.PHONY : src/control/TCommand.i

# target to preprocess a source file
src/control/TCommand.cpp.i:
	$(MAKE) -f CMakeFiles/acs.dir/build.make CMakeFiles/acs.dir/src/control/TCommand.cpp.i
.PHONY : src/control/TCommand.cpp.i

src/control/TCommand.s: src/control/TCommand.cpp.s

.PHONY : src/control/TCommand.s

# target to generate assembly for a file
src/control/TCommand.cpp.s:
	$(MAKE) -f CMakeFiles/acs.dir/build.make CMakeFiles/acs.dir/src/control/TCommand.cpp.s
.PHONY : src/control/TCommand.cpp.s

src/control/TLogSystem.o: src/control/TLogSystem.cpp.o

.PHONY : src/control/TLogSystem.o

# target to build an object file
src/control/TLogSystem.cpp.o:
	$(MAKE) -f CMakeFiles/acs.dir/build.make CMakeFiles/acs.dir/src/control/TLogSystem.cpp.o
.PHONY : src/control/TLogSystem.cpp.o

src/control/TLogSystem.i: src/control/TLogSystem.cpp.i

.PHONY : src/control/TLogSystem.i

# target to preprocess a source file
src/control/TLogSystem.cpp.i:
	$(MAKE) -f CMakeFiles/acs.dir/build.make CMakeFiles/acs.dir/src/control/TLogSystem.cpp.i
.PHONY : src/control/TLogSystem.cpp.i

src/control/TLogSystem.s: src/control/TLogSystem.cpp.s

.PHONY : src/control/TLogSystem.s

# target to generate assembly for a file
src/control/TLogSystem.cpp.s:
	$(MAKE) -f CMakeFiles/acs.dir/build.make CMakeFiles/acs.dir/src/control/TLogSystem.cpp.s
.PHONY : src/control/TLogSystem.cpp.s

src/control/TPhShifter.o: src/control/TPhShifter.cpp.o

.PHONY : src/control/TPhShifter.o

# target to build an object file
src/control/TPhShifter.cpp.o:
	$(MAKE) -f CMakeFiles/acs.dir/build.make CMakeFiles/acs.dir/src/control/TPhShifter.cpp.o
.PHONY : src/control/TPhShifter.cpp.o

src/control/TPhShifter.i: src/control/TPhShifter.cpp.i

.PHONY : src/control/TPhShifter.i

# target to preprocess a source file
src/control/TPhShifter.cpp.i:
	$(MAKE) -f CMakeFiles/acs.dir/build.make CMakeFiles/acs.dir/src/control/TPhShifter.cpp.i
.PHONY : src/control/TPhShifter.cpp.i

src/control/TPhShifter.s: src/control/TPhShifter.cpp.s

.PHONY : src/control/TPhShifter.s

# target to generate assembly for a file
src/control/TPhShifter.cpp.s:
	$(MAKE) -f CMakeFiles/acs.dir/build.make CMakeFiles/acs.dir/src/control/TPhShifter.cpp.s
.PHONY : src/control/TPhShifter.cpp.s

src/control/TTable.o: src/control/TTable.cpp.o

.PHONY : src/control/TTable.o

# target to build an object file
src/control/TTable.cpp.o:
	$(MAKE) -f CMakeFiles/acs.dir/build.make CMakeFiles/acs.dir/src/control/TTable.cpp.o
.PHONY : src/control/TTable.cpp.o

src/control/TTable.i: src/control/TTable.cpp.i

.PHONY : src/control/TTable.i

# target to preprocess a source file
src/control/TTable.cpp.i:
	$(MAKE) -f CMakeFiles/acs.dir/build.make CMakeFiles/acs.dir/src/control/TTable.cpp.i
.PHONY : src/control/TTable.cpp.i

src/control/TTable.s: src/control/TTable.cpp.s

.PHONY : src/control/TTable.s

# target to generate assembly for a file
src/control/TTable.cpp.s:
	$(MAKE) -f CMakeFiles/acs.dir/build.make CMakeFiles/acs.dir/src/control/TTable.cpp.s
.PHONY : src/control/TTable.cpp.s

src/control/ToolBoxAndUtilities.o: src/control/ToolBoxAndUtilities.cpp.o

.PHONY : src/control/ToolBoxAndUtilities.o

# target to build an object file
src/control/ToolBoxAndUtilities.cpp.o:
	$(MAKE) -f CMakeFiles/acs.dir/build.make CMakeFiles/acs.dir/src/control/ToolBoxAndUtilities.cpp.o
.PHONY : src/control/ToolBoxAndUtilities.cpp.o

src/control/ToolBoxAndUtilities.i: src/control/ToolBoxAndUtilities.cpp.i

.PHONY : src/control/ToolBoxAndUtilities.i

# target to preprocess a source file
src/control/ToolBoxAndUtilities.cpp.i:
	$(MAKE) -f CMakeFiles/acs.dir/build.make CMakeFiles/acs.dir/src/control/ToolBoxAndUtilities.cpp.i
.PHONY : src/control/ToolBoxAndUtilities.cpp.i

src/control/ToolBoxAndUtilities.s: src/control/ToolBoxAndUtilities.cpp.s

.PHONY : src/control/ToolBoxAndUtilities.s

# target to generate assembly for a file
src/control/ToolBoxAndUtilities.cpp.s:
	$(MAKE) -f CMakeFiles/acs.dir/build.make CMakeFiles/acs.dir/src/control/ToolBoxAndUtilities.cpp.s
.PHONY : src/control/ToolBoxAndUtilities.cpp.s

src/control/defasador.o: src/control/defasador.cpp.o

.PHONY : src/control/defasador.o

# target to build an object file
src/control/defasador.cpp.o:
	$(MAKE) -f CMakeFiles/acs.dir/build.make CMakeFiles/acs.dir/src/control/defasador.cpp.o
.PHONY : src/control/defasador.cpp.o

src/control/defasador.i: src/control/defasador.cpp.i

.PHONY : src/control/defasador.i

# target to preprocess a source file
src/control/defasador.cpp.i:
	$(MAKE) -f CMakeFiles/acs.dir/build.make CMakeFiles/acs.dir/src/control/defasador.cpp.i
.PHONY : src/control/defasador.cpp.i

src/control/defasador.s: src/control/defasador.cpp.s

.PHONY : src/control/defasador.s

# target to generate assembly for a file
src/control/defasador.cpp.s:
	$(MAKE) -f CMakeFiles/acs.dir/build.make CMakeFiles/acs.dir/src/control/defasador.cpp.s
.PHONY : src/control/defasador.cpp.s

src/control/main.o: src/control/main.cpp.o

.PHONY : src/control/main.o

# target to build an object file
src/control/main.cpp.o:
	$(MAKE) -f CMakeFiles/acs.dir/build.make CMakeFiles/acs.dir/src/control/main.cpp.o
.PHONY : src/control/main.cpp.o

src/control/main.i: src/control/main.cpp.i

.PHONY : src/control/main.i

# target to preprocess a source file
src/control/main.cpp.i:
	$(MAKE) -f CMakeFiles/acs.dir/build.make CMakeFiles/acs.dir/src/control/main.cpp.i
.PHONY : src/control/main.cpp.i

src/control/main.s: src/control/main.cpp.s

.PHONY : src/control/main.s

# target to generate assembly for a file
src/control/main.cpp.s:
	$(MAKE) -f CMakeFiles/acs.dir/build.make CMakeFiles/acs.dir/src/control/main.cpp.s
.PHONY : src/control/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... acs"
	@echo "... src/control/Attenuator.o"
	@echo "... src/control/Attenuator.i"
	@echo "... src/control/Attenuator.s"
	@echo "... src/control/Serial.o"
	@echo "... src/control/Serial.i"
	@echo "... src/control/Serial.s"
	@echo "... src/control/TAcs.o"
	@echo "... src/control/TAcs.i"
	@echo "... src/control/TAcs.s"
	@echo "... src/control/TCommand.o"
	@echo "... src/control/TCommand.i"
	@echo "... src/control/TCommand.s"
	@echo "... src/control/TLogSystem.o"
	@echo "... src/control/TLogSystem.i"
	@echo "... src/control/TLogSystem.s"
	@echo "... src/control/TPhShifter.o"
	@echo "... src/control/TPhShifter.i"
	@echo "... src/control/TPhShifter.s"
	@echo "... src/control/TTable.o"
	@echo "... src/control/TTable.i"
	@echo "... src/control/TTable.s"
	@echo "... src/control/ToolBoxAndUtilities.o"
	@echo "... src/control/ToolBoxAndUtilities.i"
	@echo "... src/control/ToolBoxAndUtilities.s"
	@echo "... src/control/defasador.o"
	@echo "... src/control/defasador.i"
	@echo "... src/control/defasador.s"
	@echo "... src/control/main.o"
	@echo "... src/control/main.i"
	@echo "... src/control/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

